fixed wlan-ng26-utils, added myself as the maintainer

diff --git a/core/wlan-ng26-utils/PKGBUILD b/core/wlan-ng26-utils/PKGBUILD
--- a/core/wlan-ng26-utils/PKGBUILD
+++ b/core/wlan-ng26-utils/PKGBUILD
@@ -1,3 +1,4 @@
+# Maintainer: Jens Pranaitis <jens@chaox.net>
 # Contributor: Tom Killian <tom@archlinux.org>
 
 pkgname=wlan-ng26-utils
@@ -12,18 +13,48 @@ url="ftp://ftp.linux-wlan.org/pub/linux-wlan-ng/"
 backup=(etc/wlan/wlan.conf)
 arch=('i586' 'i686' 'x86_64')
 license=('MPL')
-
 build() {
    cd $startdir/src/linux-wlan-ng-$pkgver
    patch -Np0 -i ../kernel-2.6.26.patch || return 1
    sed -i "s#TARGET_ROOT_ON_HOST=#TARGET_ROOT_ON_HOST=$startdir/pkg#;s#PRISM2_PLX=y#PRISM2_PLX=n#;s#PRISM2_PCI=y#PRISM2_PCI=n#" config.in
    patch -p1 < ../wlan-ng.patch
    make auto_config
-   make all || return 1
-   make install
+   make # this will fail but it's needed to generate some headers - don't ask ;)
+   # install utilities
+   cd src/wlanctl
+   make clean
+   make
+   install -Dm 755 wlanctl "$pkgdir"/sbin/wlanctl-ng || return 1
+   cd ../prism2/download
+   make clean
+   make
+   install -Dm 755 prism2dl "$pkgdir"/sbin/prism2dl || return 1
+   cd ../../wlancfg
+   make clean
+   make
+   install -Dm 755 wlancfg "$pkgdir"/sbin/wlancfg || return 1
+   cd ../nwepgen
+   make clean
+   make
+   install -Dm 755 nwepgen "$pkgdir"/sbin/nwepgen || return 1
+   echo "Utils finished"
+   cd ../..
+   # install config and initscript
+   cd etc/
+   make install || return 1
+   echo "config finished"
+   # install firmware
+   cd ..
+   cd src/prism2/
+   make install-firmware || return 1
+   echo "Firmware finished"
+   # install manpages
+   cd ../../man
+   make install || return 1
+   echo "Manpages finished"
    mkdir -p $startdir/pkg/etc/rc.d
    rm -r $startdir/pkg/{init.d,lib,etc/pcmcia}
-   install -m 755 $startdir/src/wlan $startdir/pkg/etc/rc.d/wlan
+   install -m 755 $srcdir/wlan $startdir/pkg/etc/rc.d/wlan
 }
 md5sums=('96130b36f9674521b08fb3e2a6ac0382'
          '706464f9e6e127558aed25b9f454f905'
